/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.usuario;

import java.util.ArrayList;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import javax.swing.table.DefaultTableModel;
import model.comum.pizza.Pizza;
import view.montarPizza.JMontadoraPizza;
import view.usuario.dto.Cliente;

/**
 *
 * @author paulo
 */
public class SClient extends javax.swing.JFrame {

    public ArrayList<Cliente> Cl = new ArrayList<>();
    public Cliente SeleClient = new Cliente();
    public List<Pizza> pizzas;

    /**
     * Creates new form SClient
     * @param pizzas
     */
    public SClient(List<Pizza> pizzas) {
        this.pizzas = pizzas;
        initComponents();
        Populate();
    }

    private void Update(Cliente c) {
        Cl.add(c);

        DefaultTableModel model = (DefaultTableModel) TClient.getModel();
        model.getDataVector().removeAllElements();
        model = fill(Cl, model);
        TClient.setModel(model);

    }

    private void Populate() {
        Cliente c = Fill("Jack", "Sao Paulo", "Av. Paulista", "26", "12", "987749898");
        Cl.add(c);
        c = Fill("Edd", "Boituva", "Castelo Branco", "38", "23", "83214341");
        Cl.add(c);
        c = Fill("Johnny", "Sorokaba", "Alguma avenida", "38", "23", "83434341");
        Update(c);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TClient = new javax.swing.JTable();
        BtnAdd = new javax.swing.JButton();
        BtnGo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnAdd1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cidade", "Rua", "Número", "Complemento", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TClient);

        BtnAdd.setText("Adicionar");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnGo.setText("Finalizar");
        BtnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setText("Cliente");

        BtnAdd1.setText("Voltar");
        BtnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BtnAdd)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdd1)
                    .addComponent(BtnGo))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        AdicionarClient AdicionarClient = new AdicionarClient(this, rootPaneCheckingEnabled);
        AdicionarClient.setVisible(true);
        if (AdicionarClient.getClient() != null) {
            Update(AdicionarClient.getClient());
        }
    }//GEN-LAST:event_BtnAddActionPerformed

    private void TClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TClientMouseClicked
        TClient.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                SeleClient.setNome((String) TClient.getValueAt(TClient.getSelectedRow(), 0));
                SeleClient.setCidade((String) TClient.getValueAt(TClient.getSelectedRow(), 1));
                SeleClient.setRua((String) TClient.getValueAt(TClient.getSelectedRow(), 2));
                SeleClient.setNumero((String) TClient.getValueAt(TClient.getSelectedRow(), 3));
                SeleClient.setComplemento((String) TClient.getValueAt(TClient.getSelectedRow(), 4));
                SeleClient.setTelefone((String) TClient.getValueAt(TClient.getSelectedRow(), 5));
            }
        });
    }//GEN-LAST:event_TClientMouseClicked

    private void BtnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGoActionPerformed
        TelaFinalizar TelaFinalizar = new TelaFinalizar();
        TelaFinalizar.setVisible(true);
        /*
        Eu não sei como o vinicius quer que eu passe a variável 'cliente'.
        O cliente a ser passado é a variável 'SeleCliente"
         */
    }//GEN-LAST:event_BtnGoActionPerformed

    private void BtnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdd1ActionPerformed
        new JMontadoraPizza(this.pizzas).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAdd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SClient(new ArrayList<>()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnAdd1;
    private javax.swing.JButton BtnGo;
    private javax.swing.JTable TClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private Cliente Fill(String Nome, String Cidade, String Rua, String numero, String Complemento, String telefone) {
        Cliente c = new Cliente();
        c.setNome(Nome);
        c.setCidade(Cidade);
        c.setRua(Rua);
        c.setNumero(numero);
        c.setComplemento(Complemento);
        c.setTelefone(telefone);
        return c;
    }

    private DefaultTableModel fill(ArrayList<Cliente> Cl, DefaultTableModel model) {
        for (int i = 0; i < Cl.size(); i++) {
            String Nome = Cl.get(i).getNome();
            String Cidade = Cl.get(i).getCidade();
            String Rua = Cl.get(i).getRua();
            String Numero = Cl.get(i).getNumero();
            String Complemento = Cl.get(i).getComplemento();
            String Telefone = Cl.get(i).getTelefone();
            if (Cl.get(i).getNome() != null) {
                Object[] data = {Nome, Cidade, Rua, Numero, Complemento, Telefone};
                model.addRow(data);
            }
        }
        return model;
    }
}
